apiVersion: v1

kind: Service
metadata:
  name: web-app-service
  labels:
    env: dev

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    application: web-app
